### ISSUE TITLE
New website wireframe

### ISSUE THREAD

**Issue by rajataaron** [GNDG/gndg.github.io#9]
This should be the design of website

![gndg-wireframe](https://user-images.githubusercontent.com/7890954/27142022-74a6eac8-5147-11e7-82b7-63a61368ab2a.png)

**Comment by rajataaron** [comment]
![gndg-website](https://user-images.githubusercontent.com/7890954/27175504-03c9304a-51dd-11e7-92f5-2744a06f283b.png)
As per some issues i have designed new layout for website simple and elegant.

**Comment by realslimshanky** [comment]
Hi, I'm working to fix this issue.
